name: proxy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - fastapi==0.115.0
    - uvicorn[standard]==0.30.6
    - httpx[http2]==0.27.2
    - cachetools==5.3.3
    - loguru==0.7.2
    - prometheus-client==0.20.0
    - pytest==8.3.2
    - pytest-asyncio==0.24.0
    - asgi-lifespan==2.1.0
    - h2==4.1.0
